export const HOMEPAGE_PATH = "/"
export const BOARD_PATH = "/board"
export const VOLUNTEERS_PATH = "/volunteers"
export const ACTIVITIES_PATH = "/activities"
export const CONTACT_PATH = "/contact"
export const FINANCE_PATH = "/finance"
